comur_api_upload:
    path: /upload #/{paramName}/{uploadUrl}/{webDir}/{minWidth}/{minHeight}
    defaults: {_controller: "IMGImageBundle:Upload:uploadImage"}
    options:
        expose: true

comur_api_crop:
    path: /crop #/{uploadUrl}/{webDir}/{imageName}/{x}/{y}/{w}/{h}/{tarW}/{tarH}
    defaults: {_controller: "IMGImageBundle:Upload:cropImage"}
    options:
        expose: true

comur_api_image_library:
    path: /image-library
    defaults: {_controller: "IMGImageBundle:Upload:getLibraryImages"}
    options:
        expose: true
